# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4acb9b17ab022b516156e7ea4135f0dbe1655bc9c0fbd88721c9d54c5fcc71714bb9c47a9806e8c901202c10ce2b2c1d9cc3ea6e5da049927562c9962adcc239

test:
  secret_key_base: 0e56c73d69ee3c36cb396bf63a2110f2b2acfca32250087a84713ad5a05deea2408692b15b1755293612c110456e5ebb25b6c27b5d144b68d99e2ad45759f40c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
